[project]
name = "duck-db-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13.1"
dependencies = [
    "duckdb>=1.2.1",
    "fastapi>=0.115.11",
    "pandas>=2.2.3",
    "python-multipart>=0.0.20",
    "uvicorn>=0.34.0",
]
